## https://docs.travis-ci.com/user/languages/r/
## https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
r: devel
sudo: false
cache: packages

## https://docs.travis-ci.com/user/installing-dependencies/
## this is the only extra package we need, and it's whitelisted,
## so we can leave 'sudo: false' above and get a big speed boost
addons:
  apt:
    packages:
    - texlive-latex-extra

r_github_packages:
  - jimhester/covr

env:
 - LME4_TEST_LEVEL=2

## need travis_wait because checks take 10+ minutes ...
after_success:
  - travis_wait Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - test_mods
